name: Excel Operations

on: 
  workflow_dispatch:  # Allows manual trigger from GitHub Actions UI

jobs:
  run_excel_script:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          pip install pandas openpyxl xlrd

      - name: Run Excel Script
        run: python excel_operations.py
      
      - name: Commit & Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}  # Use PAT for authentication
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/anavartpandya/excel_automation.git
          git add output.xlsx
          git commit -m "Updated output.xlsx from GitHub Actions" || echo "No changes to commit"
          git push origin main
